name: Tag latest

on:
  push:
    branches:
      - master

jobs:
  tag:

    runs-on: ubuntu-latest

    steps:

      - name: publish docker
        uses: LucienShui/Publish-Docker-Github-Action@2.7.1
        with:
          name: registry.cn-hangzhou.aliyuncs.com/pasteus/github-mvn-repo:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.cn-hangzhou.aliyuncs.com
          dockerfile: Dockerfile

      - name: Tag latest and push
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}
        run: |
          git clone https://github.com/PasteUs/MavenRepository.git push_dir
          cd push_dir
          git config user.name "PasteUs Bot"
          git config user.email "${GITHUB_USERNAME}"
          git tag -f latest master
          git push -f https://${GITHUB_PASSWORD}@github.com/PasteUs/MavenRepository.git latest
          cd ..
          rm -rf push_dir