name: Tag latest

on:
  push:
    branches:
      - master

jobs:
  tag:

    runs-on: ubuntu-latest

    steps:
      - name: Tag latest and push
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}
          GITHUB_REPOSITORY: github.com/PasteUs/MavenRepository.git
        run: |
          git clone https://${GITHUB_REPOSITORY} push_dir
          cd push_dir
          git config user.name "PasteUs Bot"
          git config user.email "${GITHUB_USERNAME}"
          git tag latest master
          git push https://${GITHUB_PASSWORD}@${GITHUB_REPOSITORY} latest
